### ISSUE TITLE
edit Citations table

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#10]
**What module(s) and tab(s) would this change affect?**
TAXONOMY MODULE, Citations tab

**Is your request related to a problem? Please describe.**
It is frustrating to not see the information we record in the Citations table.

**Describe the solution you'd like**
We would like to see information from fields 'Remarks' and 'Occurrences' in the Citations table instead of 'Verified By' and 'Type Status'.

**Comment by ljwalker** [comment]
![Screen Shot 2020-03-26 at 5 35 45 PM](https://user-images.githubusercontent.com/11181096/77709841-8de4b480-6f89-11ea-927f-36353883d569.png)

Reduce the size of the _Cited In_,  Verified By_, and _Primary Citation_ columns to make more space for a new _Occurrences_ column. The new column should go between _Cited In_ and _Verified By_.

**Comment by ljwalker** [comment]
Adding image (mockup from Bill) to illustrate changes requested. Note new "Occurrences" column in the _Citations_ table:

![etaxonomy_Citations 2 Tab-2](https://user-images.githubusercontent.com/11181096/110993964-e6dd6200-832c-11eb-8625-46fd91a3b699.JPG)

**Comment by jahook** [comment]
![Milestones_edit Citations table #10](https://user-images.githubusercontent.com/97756298/212436374-26595f95-e917-4cb1-a97d-0c02617a879a.png)


All changes were made during the EMu upgrade.
