### ISSUE TITLE
edit Validity table

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#11]
**What module(s) and tab(s) would this change affect?**
TAXONOMY MODULE, Validity tab

**Is your request related to a problem? Please describe.**
It is frustrating to not see the information we record in the Validity table.

**Describe the solution you'd like**
Add column in table to show data ‘Comments’ and make ‘Reason’ column very small (since it cannot be deleted?).

**Comment by ljwalker** [comment]
![Screen Shot 2020-03-27 at 12 15 32 PM](https://user-images.githubusercontent.com/11181096/77792127-09477400-7025-11ea-81eb-4f283f62972d.png)

>... make ‘Reason’ column very small (**since it cannot be deleted?**).
- Related: The _Reason_ field cannot be searched, nor can it be edited for new records, which is great. However, it can still be edited on **existing** records. Is there any way this field can be grey out for existing EMu taxonomy records?
