### ISSUE TITLE
add column in table to show data for 'Currently Accepted'

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#14]
**What module(s) and tab(s) would this change affect?**
TAXONOMY MODULE, Hierarchy tab

**Is your request related to a problem? Please describe.**
EMu does not distinguish between accepted and unaccepted names in the Hierarchy tab, and this is confusing when you are viewing it.

**Describe the solution you'd like**
Add column in table to show data for 'Currently Accepted' (from Invertebrates tab).

**Comment by ljwalker** [comment]
This new column should be relatively narrow (to display just "yes", "no", or "unknown"), and it can go between _Taxon_ and _Rank_.

**Comment by ljwalker** [comment]
Request may not be possible. Bill is inquiring.

**Comment by ljwalker** [comment]
Mockup from Bill below. Note new "Accepted?" column:

![etaxonomy_Hierachy](https://user-images.githubusercontent.com/11181096/110842593-25571c00-825c-11eb-8cb9-8b23d66a887d.JPG)

**Comment by jahook** [comment]
Per Bill: Axiell could not complete this request.  Unfortunately they left it partially finished before realizing it could not be done. The next version of EMu will have the old columns reinstated. For now the hierarchy tab works as expected, but the columns are misnamed.
![Milestones_add column in table to show data for 'Currently Accepted' #14](https://user-images.githubusercontent.com/97756298/223289779-5c0958d0-d130-472c-a738-e51bdb2a823b.png)

**Comment by jahook** [comment]
![Milestones_add column in table to show data for 'Currently Accepted' #14](https://user-images.githubusercontent.com/97756298/227666841-75706a22-760a-4489-92ce-4ca1f92dd087.png)
The original columns reinstated during the 2023 EMu Upgrade.
