### ISSUE TITLE
adjust behavior of modifiers so that “sp.” and “indet.” are automatic

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#21]
**What module(s) and tab(s) would this change affect?**
CATALOGUE MODULE, Identification (1) tab

**Is your request related to a problem? Please describe.**
The way taxonomic modifiers currently work for specimen identifications is unintuitive and inefficient, and presents an opportunity for data quality issues.

**Describe the solution you'd like**
Adjust behavior of modifiers so that “sp.” and “indet.” are automatic.

**Comment by ekrimmel** [comment]
From Bill, 2019-03-19:

***Currently, this is how the modifiers work:***

Excluding cf., aff., and nr., ALL other modifiers, such as n. sp., ?, sp., indet., nov., sp. A, or anything else, will be appended to the end of the taxon, after the specified Modifier Rank.

Therefore: Select Class taxon record Cephalopoda and specify modifier rank = Class will results in: Cephalopoda indet.

Exceptions occur below the rank of Genus. Genus, Subgenus, and species are always included to retain the binomial:
- Calycoceras (Eucalycoceras) ?
- Calycoceras (Eucalycoceras) newboldi ?
- Calycoceras (Eucalycoceras) newboldi spinosa ?

***For Modifiers cf., aff., or nr.***
Modifier Rank = species

The Modifier is placed between Genus and Species or between subgenus and species if the taxon includes subgenus.  Subspecies will not be displayed.

Examples:
- *Corixa cf. elegans*
- *Calycoceras (Newboldiceras) aff. asiaticum*

***Modifiers cf., aff., or nr.***
Modifier Rank = subspecies

The Modifier is again placed between Genus and Species or between subgenus and species if the taxon includes subgenus, but the subspecies will display.

Examples:
- *Coniontis aff. abdominalis caseyi*
- *Calycoceras (Eucalycoceras) cf. newboldi spinosa*

***Currently, cf., aff. and nr. are never placed anywhere else.***

I believe you want cf., aff., and nr. placed between Family and Genus if a Genus ranked taxon is selected and the modifier is Genus.   

Example: *Tenebrionidae cf. Coniontis*

Are there other instances where you want cf., aff., or nr. to behave in this manner?  Please include all caveats. In other words, if you select a subgenus taxon and modifier genus, do you want the result to be *Cerambycidae cf. Mesosa (Aplocnemia)*? Do you want subfamilies included or hidden? Does cf. appear after order or any other ranks? Is it possible to have something like *Carabidae cf. Cicindela haemorrhagica*?  

Are there any other behaviors the current Modifier is not allowing you to make?"

**Comment by ekrimmel** [comment]
Austin says leave the behavior of cf., nr., aff. alone for now. Our real problem is that we need “sp.” and “indet.” to be applied automatically, perhaps when an identification gets packaged together as *Modified Taxon*??

Any identification where the **lowest rank equals "genus"** needs to have "sp." appended to the end of the identification.

Any identification where the **lowest rank is anything above genus** needs to have "indet." appended to the end of the identification.

Ideally we **never** have to type/select "sp." or "indet." anywhere. These aren't really even modifiers, they are a formatting preference...

**Comment by wlmertz** [comment]
Currently, some specimen identifications do not meet this formatting preference.  There are genera with .isp, .aff, .indet, .cf , and empty suffixes in your catalog.  Do you want a list, or should I make all rank=genus sp. suffix?  Or will there be instances when rank=genus will not have an sp. suffix?

**Comment by ekrimmel** [comment]
A list would be very helpful, thanks! I suspect that most are our mistake, although "isp." is an issue and something we did not consider. We use "isp." in place of "sp." if the taxon is an ichnospecies (in EMu, any taxonomy record where *Phylum*="Ichnofossil").

**Comment by ekrimmel** [comment]
Thanks for the list! Most of the rows on it are mistakes on our part (hence why we'd like to make this automated). I fixed the weird ones, left the ones that implementing these rules would fix, and realized we forgot three special circumstances in our initial rules. So... our amended rules would be:

- Any identification where the **lowest rank equals "genus" or "subgenus"** needs to have "sp." appended to the end of the identification.
    - **Except where *Phylum* = "Ichnofossil"**, in which case "isp." should be appended to the end of the identification

- Any identification where the **lowest rank is anything above genus** needs to have "indet." appended to the end of the identification.
    - **Except where *Phylum* = "Unsorted fossils"**, in which case there should be nothing appended to the end of the identification

**Comment by ljwalker** [comment]
This issue appears to be fixed with the EMu upgrade.
