### ISSUE TITLE
move collector and collecting data to Sites

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#22]
**What module(s) and tab(s) would this change affect?**
CATALOGUE, Invert. Paleo. tab / SITES MODULES, IP Locality (1) tab

**Is your request related to a problem? Please describe.**
LACMIP specimens typically have collecting event information recorded at the site level, not the specimen level. Having to record this at the specimen level in EMu is incredibly inefficient and leads to poor data quality.

**Describe the solution you'd like**
Remove this table from the Catalogue module entirely. Move Collector and Collecting Date info to Sites. Get rid of ‘Uncertain’. Add a field for 'Verbatim collecting date.'

**Comment by ekrimmel** [comment]
<img width="620" alt="emu_catalogue-invertpaleo_2019-03-19" src="https://user-images.githubusercontent.com/11165319/54624425-90cdd080-4a2a-11e9-8123-1735f75527df.png">

**Comment by ekrimmel** [comment]
Modified design from Bill, 2019-03-19:

"Collectors has been removed. It will be added to Sites as a single line entry instead of a table, as it was in Catalog. Removing Collectors gave me space to stretch REMARKS and IP PUBLICATIONS."

![ecatalogue_AllIPaTab](https://user-images.githubusercontent.com/11165319/54624609-f457fe00-4a2a-11e9-9d7b-af8abf51e2dd.jpg)

**Comment by ekrimmel** [comment]
Modified design from Bill, 2019-03-19:

"For the IP Locality (1) tab in SITES I tried to squeeze Collector information (names and dates) into the lower right.  To create enough space I moved the Uncertain Locality checkbox out of the Geographic Details section and placed it at the top.  Collector Name will have a lookup list.  Start and End Dates will be true date fields.  Verbatim Date will be open text."

![esites_AllIPL1Tab](https://user-images.githubusercontent.com/11165319/54625545-b956ca00-4a2c-11e9-8ade-42737d3f7e82.jpg)

**Comment by ekrimmel** [comment]
Alternative modified design from Bill, 2019-03-19:

"This version of IP Locality (1) has the Geographic Details to the Right, and the source and Verbatim Locality were placed inside the Geographic Details group.  I also moved Geographic Citations to IP Locality (2) and removed Loc. Summary completely.  These changes gave me enough room to place TRS on this tab."

![esites_AllIPL1Tab_alt2](https://user-images.githubusercontent.com/11165319/54625644-eacf9580-4a2c-11e9-99a5-5fc6dadd9282.jpg)

**Comment by wlmertz** [comment]
95% of the values have been moved.  Awaiting decision on remaining problematic collector data.  The problematic data includes collector information that differs from specimen to specimen within the same site.
