### ISSUE TITLE
move accession data to Sites

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#23]
**What module(s) and tab(s) would this change affect?**
CATALOGUE, Invert. Paleo. tab / SITES MODULES, IP Locality (1) tab

**Is your request related to a problem? Please describe.**
LACMIP specimens typically have accession information recorded at the site level, not the specimen level. Having to record this at the specimen level in EMu is incredibly inefficient and leads to poor data quality.

**Describe the solution you'd like**
Remove the fields 'Accn. No.' and 'Accn. Lot' from the Catalogue module and add them to the Sites module.

**Comment by ekrimmel** [comment]
<img width="620" alt="emu_catalogue-invertpaleo_2019-03-19" src="https://user-images.githubusercontent.com/11165319/54624312-60863200-4a2a-11e9-8139-6d2e04aae23f.png">

**Comment by ekrimmel** [comment]
Modified design from Bill, 2019-03-19:

"This retains the *Accn. Lot* and *Accn. No.* fields in Catalog for now, but they can be hidden and IP can be prohibited from using them. We will add *Accn. No.* to Sites, *Accn. Lot* may be problematic. I am waiting for some answers from Axiell."

![ecatalogue_AllIPaTab](https://user-images.githubusercontent.com/11165319/54624521-bfe44200-4a2a-11e9-8428-8e5ed1600ca9.jpg)

**Comment by ekrimmel** [comment]
From Bill, 2019-03-19:

"It seems we already discussed this and it was decided to keep these fields in Catalog, since Accessions has a reverse link back to Catalog, but not to Sites.  The Axiell thinking is that Specimens are accessioned, not localities."

**Comment by wlmertz** [comment]
We can place "Accession Number" in SITES IP Locality (1) at the top between Loc ID and Uncertain.  However, this will be a generic text field, not a link to Accession Lots.  Links to Accession Lots is done through Catalog.  I'd recommend retaining Accession Number in Catalog, even if it's hidden or set to Read-Only.

**Comment by ekrimmel** [comment]
Yes, we discussed and also agree that we should leave the accession fields as they are for now. Does our registrar use accession number, or do you know what the purpose of that field is?

**Comment by wlmertz** [comment]
Accession Number is a free text field.  It is not attached to the Registrar or Accession Lots module.  It is merely used for reference within collection departments.  Not surprisingly, a collection will have "Accession Numbers" they want to note, but are either "unofficial" Accession Numbers or numbers which the Registrar's Office has yet to create an Accession Lots record.

**Comment by ekrimmel** [comment]
Ah ok, that makes sense. I'm going to leave this issue open because it hasn't really been resolved, but for now I think there's nothing else we need to do.

**Comment by wlmertz** [comment]
Note, "Accn. No." on the Invert. Paleo. tab is known as "Registrar Number" on the Registrar tab.  However, they are the same field.  If you edit one, the other will be change as well.  

No need to change "Accn. No." label on the Invert. Paleo. tab.    The value in that field is nearly always an accession number, but can include some values that are not technically accession numbers, hence the Registrar's Office decision to label it "Registrar Number" on their tab.

**Comment by ljwalker** [comment]
Please have Axiell add a text field for _Registrar No._ to the Sites module, preferably on the upper left corner of the Notes tab. This field should be wide enough so that the entire number is visible.

**Comment by ljwalker** [comment]
Remaining design issues (creation of new field, _Registrar No._), related to issue #23  to be resolved as part of issue #54.
