### ISSUE TITLE
redesign "Invert. Paleo" tab

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#24]
**Redesign Mock-up v1**

![ecatalogue_AllIPaTab](https://user-images.githubusercontent.com/11165319/54773536-079fd080-4bc7-11e9-8355-cd08b40d7ec8.jpg)

**Comments on Mock-up**
- Can we change the label *Disp.* to *Disposition*? It looks like we have space.
- Can we move the *IP Publications* table down and increase the height of *Lot Remarks* by one line? *IP Publications* rarely has more than one row.

**This redesign will resolve GitHub issue #22.**

**Comment by wlmertz** [comment]
![ecatalogue_AllIPaTab](https://user-images.githubusercontent.com/48773905/54839492-3467ec80-4c88-11e9-97d7-648f012734ca.jpg)

**Comment by wlmertz** [comment]
Also, Lot Remarks should stretch when you expand the window.

**Comment by ekrimmel** [comment]
@wlmertz this looks good to go!

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16**

<img width="840" alt="Screen Shot 2019-05-16 at 1 52 13 PM" src="https://user-images.githubusercontent.com/11165319/57886359-dff17100-77e1-11e9-9f7e-ce52c81248d4.png">

EK has briefly reviewed.
