### ISSUE TITLE
redesign "IP Locality (1)" tab

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#25]
**Redesign Mock-up v1**

![esites_AllIPL1Tab](https://user-images.githubusercontent.com/11165319/54774554-49ca1180-4bc9-11e9-898d-561cddc8c907.jpg)

**Comments on Mock-up**
We like the first version of the redesign (no TRS data on this tab). A few additional comments/requests:
1. If space allows, change *State/Prov.* to *State/Province*
2. If space allows, change *County/Dist.* to *County/District*
3. Change *NearestPlace* to *Nearest Place*
4. Make *Start Date* and *End Date* data entry fields the same width
5. Do the *Start Date* and *End Date* fields have a calendar lookup? We'd like this, please
6. Change *Verbatim Date* to *Verbatim*
7. Ideally we'd like more space for *Verbatim Locality*–could it work to get rid of *Loc. Summary* and move the *Alternate Loc ID* and *Geographic Citation* tables up in order to also move the *Collector* table up, in order to give *Verbatim Locality* the entire width span again?

**This redesign will resolve GitHub issue #22.**

**Comment by wlmertz** [comment]
![esites_AllIPL1Tab](https://user-images.githubusercontent.com/48773905/54838774-aa6b5400-4c86-11e9-9f6f-88e48d8d8b9b.jpg)

**Comment by ekrimmel** [comment]
@wlmertz this looks good to go!

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16**

<img width="801" alt="Screen Shot 2019-05-16 at 1 53 58 PM" src="https://user-images.githubusercontent.com/11165319/57886464-234bdf80-77e2-11e9-9102-3ed680d7b261.png">

EK has reviewed briefly.

**Minor things to fix:**
- *State/Province.* should be *State/Province* (no period)
- *County/District.* should be *County/District* (no period)

**Comment by wlmertz** [comment]
Fix request submitted to Axiell 2019-05-16
State/Province. should be State/Province (no period)
County/District. should be County/District (no period)

**Comment by ljwalker** [comment]
This issue has been resolved by the EMu upgrade.
