### ISSUE TITLE
redesign "IP Locality (2)" tab

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#26]
**Redesign Mock-up v1**

![esites_AllIPL2Tab](https://user-images.githubusercontent.com/11165319/54775297-eccf5b00-4bca-11e9-8345-2522b386d571.jpg)

**Comments on Mock-up**
We like the first version of the redesign (retaining TRS data on this tab). A few additional comments/requests:
1. Change *Deg. of Lithification* to *Lithification*
1. Change *Preserv. Quality* to *Preservation*
1. Reorder the fields below *Member* as (top to bottom): *Biostrat. Zone*, *Strat. Details*, *Lithology*, *Lithification*, *Preservation*
1. We would love to have at least two line-heights visible for *Strat. Details*–could we get this by placing *Lithification* and *Preservation* on the same line (the fields can be very short)? Or is there any room to scoot the *TRS* table down? We will pretty much never have more than one row in *TRS*.

**This redesign will resolve GitHub issues #19 and #20.**

**Comment by wlmertz** [comment]
![esites_AllIPL2Tab](https://user-images.githubusercontent.com/48773905/54793795-70a43a00-4c01-11e9-9496-e2f7aabd3fec.jpg)

**Comment by ekrimmel** [comment]
This looks good to go, now that we've settled on leaving TRS data on this tab per issue #27.

**Comment by wlmertz** [comment]
Strat. Details: Text, 1000 characters
Lithology, Lithification, and Preservation: Text, 100 characters.
Contact me if any should be adjusted.

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16**

<img width="821" alt="Screen Shot 2019-05-16 at 1 58 21 PM" src="https://user-images.githubusercontent.com/11165319/57886747-ce5c9900-77e2-11e9-852b-8b80b4073308.png">

EK has reviewed briefly.

**Comment by ljwalker** [comment]
This issue has been resolved by the EMu upgrade.
