### ISSUE TITLE
redesign "Lat/Long" tab

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#27]
**Redesign Mock-up v1**

![esites_AllLatTab2](https://user-images.githubusercontent.com/11165319/54775948-44ba9180-4bcc-11e9-9bc2-1f03a16a3e30.jpg)

**Comments on Mock-up**
If this is going to be a new tab anyway, we have some additional requests...
1. Delete *Comment* in the *Latitude/Longitude Details* table
1. Change *Determined By* to *Determination By*
1. Delete *Verification* (you already included *Georef. Verification Status*, which actually we can just name *Verification Status*)
1. Delete *Geometry*
1. Do we have to keep all the centroid fields (*Derive Centroid*, *Centroid Latitude (DMS)*, *Dec.*, *Centroid Longitude*, *Dec.*)? If not let's delete them.
1. If we got rid of the centroid fields then we would like to have the remaining fields in this section split left-right as such:

    left | right
    --- | ---
    *Radius (Numeric)* | *Determination Source*
    *Units* | *Determination Method*
    *Datum* | *Determination By*
    *Preferred* | *Determination Date*
    *Verification Status* | [blank]

 1. If we got rid of the centroid fields then we would like to see *Latitude (Dec.)* and *Longitude (Dec.)* in the *Latitude/Longitude List* table instead of *Centroid Latitude (DMS)* and *Centroid Longitude*.
1. Is there any way that the TRS table could fit on this tab instead of on *IP Locality (2)*?

**This redesign will resolve GitHub issues #15, #16, #17 and #18.**

**Comment by wlmertz** [comment]
To help you decide whether to remove certain fields please check EMu help:
[http://help.emu.axiell.com/v5.1/en-US/Topics/EMu/Lat%20Long%20Display%20tab.htm?Highlight=lat/long]

**Comment by ekrimmel** [comment]
Read through Axiell's documentation and nothing there changes how we feel about our requests to remove fields.

**Comment by wlmertz** [comment]
Will IP ever have a polygon site?  In other words, a site with more than one coordinate?  I don't mean a Site with multiple sets of data (old data and updated data).  I mean, instead of a point, it's a line or a polygon.

**Comment by ekrimmel** [comment]
Are you thinking about the *Geometry* field? Likely we will never be using EMu for polygon geodata. If we *did* have a simple polygon then the vertices would go in the *Latitude/Longitude* table. And if we had a more complicated polygon, we'd rather just attach a WKT file to the Site record, or copy this data into the notes field. Our thought is that *Geometry* just seems like a trash basket waiting to happen...

**Comment by wlmertz** [comment]
In that case, I can request that the first Latitude/Longitude listed is placed in the latitude/longitude list, instead of the Centroid.  In Geometry this would be a line, triangle, or polygon.

**Comment by ekrimmel** [comment]
Requesting that the first latitude/longitude listed is placed in *Latitude/longitude List*, instead of the centroid sounds good.

**Comment by wlmertz** [comment]
_8. Is there any way that the TRS table could fit on this tab instead of on IP Locality (2)?_

Yes.  There are 9 fields, excluding Notes.  If you think they won't be too small, I can spread them 3 across.  Can you give me the order they should be in?  If some must be wider, please keep them in the same column.

**Comment by wlmertz** [comment]
TRS data will not be related to the Latitude/Longitude data.  It will be "outside" of the Latitude/Longitude List.

**Comment by ekrimmel** [comment]
If the Lat/Lon tabs were to be in three columns, we'd want:

left | center | right
--- | --- | ---
*Radius (Numeric)* | *Determination Source* | *Determination By*
*Units* | *Determination Method* | *Determination Date*
*Datum* | *Verification Status* | *Preferred*

**Comment by wlmertz** [comment]
Sorry, I can't quite squeeze TRS into Lat/Long.  Will TRS ever have more than one line of values?  Does it have to be a table?

**Comment by ekrimmel** [comment]
It does not need to be a table!

**Comment by wlmertz** [comment]
I'll have to ask Axiell if Labels can be anchored above fields.  Or if a one-line table is possible.  It's a very tight fit.  We may have to go back to leaving TRS on IPLocality (2).

**Comment by wlmertz** [comment]
![esites_AllLatTab3](https://user-images.githubusercontent.com/48773905/54858948-2dab9a80-4cc5-11e9-8a18-8978635e41be.jpg)

**Comment by ekrimmel** [comment]
It's not a big deal if it has to get left on *IP Locality (2)*! I think that would be preferable to where it is in the latest screenshot because here it appears related to each row of the Lat/Lon table when it actually is not.

**Comment by wlmertz** [comment]
Correct.  We will leave TRS in IP Locality(2).  Do you want the above with a taller Notes field?  Or do you want to revert to your two-column idea?

**Comment by ekrimmel** [comment]
Ok, sounds good. And let's revert to the two column layout, please.

**Comment by wlmertz** [comment]
![esites_AllLat2Tab](https://user-images.githubusercontent.com/48773905/55031872-d7906d00-4fcc-11e9-89f5-38621a4b7c4f.jpg)

Please verify changes.

**Comment by ekrimmel** [comment]
Looks ready to go, thanks!

**Comment by wlmertz** [comment]
Latitude/Longitude List at bottom:  Corrected "Determined By".  It is now "Determination By".

**Comment by ekrimmel** [comment]
**Bill**: How many characters should the new Verification Status Field on new Lat/Lon tab hold?  The default for this kind of field is 20 characters.  Is that fine?

**Erica**: This is a dwc field with recommendations for controlled vocabulary, two of which are 21 characters ("requires verification" and "verified by collector"). So 20 won't work but I think 25 characters would be sufficient...

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16**

<img width="817" alt="Screen Shot 2019-05-16 at 2 01 18 PM" src="https://user-images.githubusercontent.com/11165319/57886905-1a0f4280-77e3-11e9-97f7-f10ada6fba6e.png">

EK has reviewed briefly. *Verification Status* is the correct length.

**Minor things to fix:**
- align *Radius (numeric)* to the labels below
- did we want to include *Preferred* in the list view? We hadn't in the design request.

**Comment by wlmertz** [comment]
- align Radius (numeric) to the labels below
Another oddity of Marconi (or how local and remote screen sizes affect display).  The label is aligned on my computer.  However, I'll ask Axiell if there is anything they can do to correct it. 

- did we want to include Preferred in the list view? We hadn't in the design request.
I can ask Axiell to always place Preferred = Yes in the first row.  This might be helpful regardless, and it will make adding Preferred to the Latitude/Longitude List redundant.  What do you think?

**Comment by wlmertz** [comment]
Axiell will add feature of placing "Preferred = Yes" row at top on record save.

**Comment by wlmertz** [comment]
Axiell was not able to make every modification we asked for.   Unfortunately, the Lat/Long tabs contain strict programming mainly due to their use of double nested tables.  Modifying them caused more problems than it solved.  We will have to revisit some of this when we upgrade to EMu 6, which corrects some of these issues.   

- Lat/Long does not automatically sort on Preferred column.  To sort, please only use "Drag and Drop" method.  Do NOT sort by column.  Sorting by column feature does not work properly.

- The Lat/Long list can only include "centroid" values.  It cannot swap out "centroids" for "first row value".

- Centroid values must be included on any Lat/Long tab since they might require modification (see next bullet point).  

- The "Derive Centroid" radio buttons have also been added.   This allows users to override the calculated centroid by selecting "User" and entering your preferred values in the centroid fields.

**Comment by ljwalker** [comment]
> did we want to include Preferred in the list view? We hadn't in the design request. I can ask Axiell to always place Preferred = Yes in the first row.
- Yes, please include _Preferred_ in the list view for the next EMu upgrade as it was missed in 2019.

**Comment by ljwalker** [comment]
As of 2021-02-26, _Preferred_ will be added to the far right side of the _Latitude/Longitude List_ table.
![Screen Shot 2021-02-26 at 3 54 30 PM](https://user-images.githubusercontent.com/11181096/109367446-f186fa00-784a-11eb-96d4-cb64339d2e09.png)

**Comment by wlmertz** [comment]
[image: esites_Lat Long 2.jpg]

I have also requested that there be only one "Preferred" allowed, and that
the "Preferred" row moves to the top upon saving the record.

Bill

**Comment by ljwalker** [comment]
Adding image to go with Bill's last comment. Note new "Preferred" column in the _Lat/Long_ list:

![esites_Lat Long 2](https://user-images.githubusercontent.com/11181096/110840726-ee800680-8259-11eb-8be3-d09896026e9a.jpg)

**Comment by jahook** [comment]
![Milestones_redesign Lat_Long tab #27](https://user-images.githubusercontent.com/97756298/212439788-8eee0c9f-2e83-4ce2-b8e5-875df71bcd06.png)

All changes were made during the EMu upgrade.
