### ISSUE TITLE
redesign "Citations" tab

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#28]
**Redesign Mock-up v1**

![etaxonomy_AllCit2Tab](https://user-images.githubusercontent.com/11165319/54777182-f5c22b80-4bce-11e9-900e-9dee8acde570.jpg)

**Comments on Mock-up**
1. Delete *Citation Details*–we know we asked for this but in talking through your redesign mockup we talked ourselves out of it...
1. Make *Occurrences* have a height of at least two lines
1. Delete the table with *Specimen* and *Type Status*
1. Show *Primary Citation* in the *Citations* table instead of *Type Status*
1. Is it possible to restrict entries so that only one row in the *Citations* table can have a *Primary Citation* value of "Yes"? Similar to how *Preferred* works on the *Lat/Long* tab? If so, can that row also always be in the top position of the *Citations* table?

**This redesign will resolve GitHub issues #5, #6, #7, #8, #9 and #10.**

**Comment by wlmertz** [comment]
I will inquire about comment 5. _Is it possible to restrict entries so that only one row in the Citations table can have a Primary Citation value of "Yes"? Similar to how Preferred works on the Lat/Long tab? If so, can that row also always be in the top position of the Citations table?_

**Comment by wlmertz** [comment]
![etaxonomy_AllCit2Tab](https://user-images.githubusercontent.com/48773905/54793037-de4e6700-4bfd-11e9-805d-473692c2ac07.jpg)

**Comment by ekrimmel** [comment]
@wlmertz aside from hearing back on comment 5, this looks good to go. Thanks!

**Comment by ekrimmel** [comment]
Note to selves: make sure that the new *Occurrences* (old *Remarks*) field **expands** when the window is resized.

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16**

<img width="839" alt="Screen Shot 2019-05-16 at 2 15 04 PM" src="https://user-images.githubusercontent.com/11165319/57887703-0b298f80-77e5-11e9-9723-75f2ec83a81b.png">

EK has reviewed briefly. For comment 5 above, EMu will automatically change an existing row from *Primary Citation* = "Yes" to *Primary Citation* = "No" if a new row is recorded as *Primary Citation* = "Yes". 

**Minor things to fix:**
- *Occurences* should be *Occurrences*
- Resizing of text boxes needs to be adjusted. *Entered By* and *Date* never required more than one line height. *Cited Locality* can expand but it is much more important that *Occurrences* expands.

**Comment by wlmertz** [comment]
Fix request submitted to Axiell 2019-05-17
Occurences => Occurrences
When expanding window, Entered By and Date will remain as one line.  Occurrences will expand vertically as Cited Locality does.

**Comment by ljwalker** [comment]
This issue has been resolved by the EMu upgrade.

**Comment by ljwalker** [comment]
> Is it possible to restrict entries so that only one row in the Citations table can have a Primary Citation value of "Yes"? Similar to how Preferred works on the Lat/Long tab? If so, can that row also always be in the top position of the Citations table?
- This was not resolved in the last EMu upgrade but is still a desired change to be made. Issue has therefore been reopened.

**Comment by wlmertz** [comment]
I believe this is possible and will be requested.  Be aware, all upgrades are on hold until next FY.

**Comment by ljwalker** [comment]
Issue appears to have been resolved.
