### ISSUE TITLE
design new "Ecology" tab

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#29]
**Redesign Mock-up v1**

![taxonomy_NewAgeTabTEST](https://user-images.githubusercontent.com/11165319/54778002-d3c9a880-4bd0-11e9-9a07-d3183cbf60ca.jpg)

**Comments on Mock-up**
We did not see anywhere on existing tabs for our new fields, and so if we're going to have to make a new tab anyway we'd like to design a tab that can capture the extent of the data Austin has in his Quaternary taxonomic dictionary. This data is used in research and collated over time in conjunction with managing taxonomy, so it makes sense to be able to store it in EMu. The fields we would like are...
1. *Age Range*, lookup
1. *Geographic Range*, lookup
1. *Type Specimens*, free text block
1. *High Lat.*, numeric
1. *Low Lat.*, numeric
1. *Min. Depth (m)*, numeric
1. *Max. Depth (m)*, numeric
1. *Depth Zone*, drop down
1. *Min. Temp (C)*, numeric
1. *Max. Temp (C)*, numeric
1. *Substrate*, drop down
1. *Abundance*, drop down
1. *Body Size (mm)*, free text line
1. *Flex Field 1*, free text line
1. *Flex Field 2*, free text line
1. *Flex Field 3*, free text line

We do not need to see the *Citations* and *Name Status (Validity)* tabs here for reference.

**Comment by ekrimmel** [comment]
We also need to include a drop down field for *Project* on this tab!

**Comment by wlmertz** [comment]
![etaxonomy_AllEcolTab](https://user-images.githubusercontent.com/48773905/54792756-bad6ec80-4bfc-11e9-86e2-c3d5f6c02518.jpg)

**Comment by ekrimmel** [comment]
@wlmertz this looks good to go!

**Comment by wlmertz** [comment]
Here are the field types I'm presuming.  Please verify. All are TEXT fields, 100 characters, except those noted below.
Type Specimens: Text, 1000 characters
Min. Temp (C) and Max. Temp (C): Integer (no decimals)
Body Size (mm): Integer (no decimals)
Min. Depth (m) and Max. Depth (m): Integer (no decimals)
Should any of those require decimals?  If so, how many?

**Comment by wlmertz** [comment]
High Lat. and Low Lat. will also be numeric, but allow for decimal places.  Should they cut off at 2 decimal places or allow for more as needed?  Also, maybe the labels should be High Lat. (dec.) and Low Lat. (dec.) to avoid confusion with DMS Lat/Long?

**Comment by wlmertz** [comment]
Sorry, I didn't notice that you wanted Body Size (mm) to be TEXT.  Is 100 characters sufficient?

**Comment by ekrimmel** [comment]
Just talked to Austin about this and...
- 100 characters for most text fields/ 1000 for *Type Specimens* is fine
- *Min. Temp (C)* and *Max. Temp (C)* need decimals (two places is fine)
- *Min. Depth (m)* and *Max. Depth (m)* can be integers
- yes, let's add units to make *High Lat. (dec.)* and *Low Lat. (dec.)*; these can cut off at two decimal places
- we'd like to modify *Body Size (mm)* – instead of a single text field, we'd like three (sorry!) new fields: 
    - *Length (mm)* - decimal
    - *Width (mm)* - decimal
    - *Height (mm)* - decimal
- we'd also like to have another text field with a 1000 character length for *Ecology Comments*
- *Flex Fields* can stay at 4 or drop down to a minimum of 2, depending on how you fit our new requests in

Thanks!

**Comment by wlmertz** [comment]
![etaxonomy_AllEcolTab](https://user-images.githubusercontent.com/48773905/55099465-f4847900-507c-11e9-9438-aab0f6166dcd.jpg)

**Comment by wlmertz** [comment]
All fields are TEXT, 100 characters except where noted below.
High Lat (dec.) and Low Lat. (dec.) are numeric, 2 decimal places 
Min Temp (C) and Max Temp (C)  are numeric, 2 decimal places
Min Depth (m) and Max Depth (m) are integers (no decimal places)
Type Specimens is Text, 1000 characters.
Length, Width, and Height are numeric, 2 decimal places 
( I assume all of these are general taxonomic characteristics, not attributed to individual specimens, otherwise Taxonomy is not the proper place for this data).

**Comment by ekrimmel** [comment]
Yes, these are general taxonomic characteristics–they make up a lot of the raw data that Austin uses for various research projects. 

All that's here looks good, although we still need a new 1000-character field for *Ecology Comments*.

**Comment by wlmertz** [comment]
Do you want Ecology Comments and Type Specimens next to each other or one above the other?  Any design/size preferences?

**Comment by ekrimmel** [comment]
*Type Specimens* above, one line height, and *Ecology Comments* below, two line heights (or whatever heights make sense is fine, but those are our preferences). Thanks!

**Comment by wlmertz** [comment]
![etaxonomy_AllEcolTab](https://user-images.githubusercontent.com/48773905/55100840-0d425e00-5080-11e9-937a-22154ad2d55f.jpg)

**Comment by ekrimmel** [comment]
Awesome, looks good to go!

**Comment by ekrimmel** [comment]
This tab is not yet in our test EMu as of 2019-05-16.

**Comment by wlmertz** [comment]
Ecology tab has been added.  Please refresh/restart EMu.
