### ISSUE TITLE
change labels on validity fields

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#30]
**What module(s) and tab(s) would this change affect?**
TAXONOMY MODULE, Validity tab

**Is your request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
We would like to change the label names of two fields to provide better clarity on what information these fields store. *Comments by* should become *Entered by*, and *Date commented* should become *Date entered*.

**Comment by wlmertz** [comment]
![etaxonomy_AllValidityICZNTab](https://user-images.githubusercontent.com/48773905/54793076-02aa4380-4bfe-11e9-9e6a-24b4717d0865.jpg)

**Comment by ljwalker** [comment]
Bill, are there more fields visible on this screenshot than what IP users can see because you're logged in as the Admin?

i.e., We still do not want the _Name Status_, _Name status attribute_, or _Reason_ fields to show up, but everything else looks good.

**Comment by wlmertz** [comment]
Sorry, the same fields hidden from you currently will continue to be hidden.  All that is changing is the label names for Comments By and Date commented (they become Entered By and Date Entered).  The tab, essentially, does not change.  
![etaxonomy_AllValidityICZNTab_IP View](https://user-images.githubusercontent.com/48773905/54859235-1621e100-4cc8-11e9-8aec-423eb0d8efae.jpg)

**Comment by ekrimmel** [comment]
@wlmertz thanks for clarifying! This tab looks good to go

**Comment by ljwalker** [comment]
One more thing!

Since we don't use _Reason_, that field does not have to show up in the nested table.

However, if _Reason_ cannot be deleted from the table, please make this column very small.

**This redesign will resolve GitHub issue #11.**

**Comment by wlmertz** [comment]
"Reason" has been used three times by IP.  I assume I can delete the Reason value for those three taxa?  IRNs 206747, 206793, 206748.  If so, I will make "Reason" smaller, but not insignificant, since other departments may also use the Validity tab.  I'll send a screenshot soon.

**Comment by wlmertz** [comment]
![etaxonomy_AllValidityICZNTab_IP View](https://user-images.githubusercontent.com/48773905/55017310-abb1bf00-4fad-11e9-843b-795410d9c0d9.jpg)

Note, REASON is Read-Only for IP.

**Comment by ljwalker** [comment]
Yes - you can delete our three instances. 

This tab looks good now. Thank you, Bill!

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16**

<img width="800" alt="Screen Shot 2019-05-16 at 2 11 27 PM" src="https://user-images.githubusercontent.com/11165319/57887564-9c4c3680-77e4-11e9-9e10-eafee25fd326.png">

EK has reviewed briefly.

**Minor things to fix:**
- *Entered by* should be *Entered By*

**Comment by wlmertz** [comment]
Fix request submitted to Axiell 2019-05-17
Entered by => Entered By
Correct name => Correct Name
Name Status (Validity) table:
Reason | Reference | Correct Name | Comments
Correct Name will display the Scientific Name in the Name Status (Validity) table.

**Comment by ljwalker** [comment]
All changes were made during the EMu upgrade.
