### ISSUE TITLE
lookup lists: "Anatomy"

### ISSUE THREAD

**Issue by ljwalker** [LACMIP/emu#32]
**What module(s) and tab(s) would this change affect?**
Module: Lookup Lists

**Is your request related to a problem? Please describe.**
EMu is not correctly populating new entries in the _Anatomy_ lookup list. Specifically, _Value 1_ is not included when a new lookup list value (_Value 2_) is added to _Anatomy_ from the Catalogue module.

**Describe the solution you'd like**
For new records in the Anatomy lookup list, _Value 1_ should autofill with "Invertebrate Paleontology".

**Additional context**
<img width="734" alt="Screen Shot 2019-03-26 at 10 45 01 AM" src="https://user-images.githubusercontent.com/11181096/55021056-5a0d3280-4fb5-11e9-9d3f-79bfd00765a8.png">
<img width="538" alt="Screen Shot 2019-03-26 at 10 54 16 AM" src="https://user-images.githubusercontent.com/11181096/55021243-a6f10900-4fb5-11e9-81ff-df44b7914f93.png">
<img width="536" alt="Screen Shot 2019-03-26 at 10 53 48 AM" src="https://user-images.githubusercontent.com/11181096/55021258-ab1d2680-4fb5-11e9-9897-be58f2ce6f31.png">

**Comment by wlmertz** [comment]
This appears to be a bug.  Adding new lookup values in the first row of a table works fine, but not in any of the subsequent rows.  I've submitted a ticket with Axiell.  I don't think this will be solved soon since it's a structural issue.  I know Anatomy (and Original Nature) have long lists, but is there any way to give me a list of all possible values so we can set these to read-only for now?  Otherwise, you may have to enter the values directly in the Lookup Lists.

**Comment by ljwalker** [comment]
For _Anatomy_: We need the flexibility to add new values, so you don't have to make it read-only for now. However, there is one value in this list that you can delete: 1306616 ("zztop").

For _Original Nature_: Nothing to change for now.

**Comment by wlmertz** [comment]
The temporary test value "zztop" has been removed.  
BTW, we can correct the issue with these lookup lists by assigning them strictly to IP only.  In other words, all other departments will be prohibited from using lookup lists specifically named "Anatomy" and "Original Nature".  If that's ok with you, I can request this fix.  (note, other departments can have lookup lists called "Anatomy2" or "AnatomyBirds"... etc., but not "Anatomy")

**Comment by wlmertz** [comment]
"Anatomy" and "Original Nature" will have one-level lookups instead of the current two-level lookups.

**Comment by wlmertz** [comment]
"Anatomy" and "Original Nature" lookup lists have been updated to display properly.  All data in column 2 has been moved to column 1.  All duplicate and extraneous values have been removed from the lookup list.  None of this affects record data.  It only applies to the lookup list itself.
