### ISSUE TITLE
Quotation marks mess up formatting and export

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#33]
**What module(s) and tab(s) does this bug affect?**
Taxonomy module, Invertebrates tab

**Describe the problem**
We need to use quotation marks in the *Genus* field occasionally to denote an improperly-positioned taxon, e.g. *"Anatina" affinis*. When we use quotation marks, EMu auto-corrects the capitalization to "anatina" when it should be "Anatina." Additionally, when we export data using the *IP Taxonomic Dictionary* report, the quotation marks break the CSV format, as shown in these two screenshots:

<img width="310" alt="Screen Shot 2019-04-19 at 8 56 30 AM" src="https://user-images.githubusercontent.com/11165319/56432137-3326e100-6281-11e9-8014-4a49d32ff62f.png">

<img width="248" alt="Screen Shot 2019-04-19 at 8 56 58 AM" src="https://user-images.githubusercontent.com/11165319/56432139-34f0a480-6281-11e9-8151-8ae8d57c10fb.png">

**Describe the solution you'd like**
We would like to be able to use quotations marks without the issues noted above.

**Additional context**
We are exporting the report as a CSV using these settings:

![image](https://user-images.githubusercontent.com/11165319/56432207-610c2580-6281-11e9-88d1-c4358e950b6a.png)

**Comment by ekrimmel** [comment]
@wlmertz is this an issue that we have the power to fix, or is it something with EMu/Crystal?

**Comment by wlmertz** [comment]
Please test again.  The report should change the Genus to proper case, and
adjust for any quotes.  This only applies in the Genus column.  If you have
similar issues in other columns please get back to me.

Bill

**Comment by ekrimmel** [comment]
Looks good now!
