### ISSUE TITLE
make ‘Author String’ a lookup list

### ISSUE THREAD

**Issue by ekrimmel** [LACMIP/emu#4]
**What module(s) and tab(s) would this change affect?**
TAXONOMY MODULE, Invertebrates tab

**Is your request related to a problem? Please describe.**
Formatting is inconsistent for author string.

**Describe the solution you'd like**
A lookup list would help users be consistent with data entry.

**Comment by wlmertz** [comment]
![etaxonomy_AllInvTab](https://user-images.githubusercontent.com/48773905/54793882-df819300-4c01-11e9-88bb-73e88338d88f.jpg)

**Comment by ekrimmel** [comment]
@wlmertz looks ready to go to us, thanks!

**Comment by wlmertz** [comment]
There should be new screenshots and comments in your issues.

**Comment by ekrimmel** [comment]
**Modifications as of 2019-05-16 look good.**

**Comment by ljwalker** [comment]
The EMu upgrade has resolved this issue.
