### ISSUE TITLE
add ID Reference to the Re-identify tool

### ISSUE THREAD

**Issue by ljwalker** [LACMIP/emu#41]
**What module(s) and tab(s) would this change affect?**
Catalogue

**Is your request related to a problem? Please describe.**
_ID Reference_ should be added to the Re-identify tool.

**Comment by jahook** [comment]
![Milestones_add ID Reference to the Re-identify tool #41](https://user-images.githubusercontent.com/97756298/212434380-40863bf8-9e90-457c-8144-c65cdacea89b.png)

The EMu upgrade has resolved this issue.
