### ISSUE TITLE
add Sampling Protocol field to Sites module

### ISSUE THREAD

**Issue by ljwalker** [LACMIP/emu#45]
**What module(s) and tab(s) would this change affect?**
_Sites_: _IP Locality(2)_

**Is your request related to a problem? Please describe.**
There is currently not a field to record _Sampling Protocol_ (=[dwc:samplingProtocol](http://rs.tdwg.org/dwc/terms/samplingProtocol)).

**Describe the solution you'd like**
We would like a dedicated field for _Samp. Protocol_ to be added to the _IP Locality(2)_ tab between _Strat. Details_ and _Lithology_.

**Additional context**
<img width="645" alt="Screen Shot 2020-09-30 at 3 13 05 PM" src="https://user-images.githubusercontent.com/11181096/94745575-d2ce1700-032f-11eb-8727-7f24abc6146d.png">

**Comment by ljwalker** [comment]
@wlmertz This request has been modified. Adding a new field for _Samp. Protocol_ would like require the _TRS_ table to be reduced to one row.

Values to be used in this field include "bulk sample", "stratigraphic sample", and "hand-picked sample".

**Comment by ljwalker** [comment]
Bill has requested new _Sampling Protocol_ field as per original mockup from March 12, 2020:

![esites_IP Locality 2](https://user-images.githubusercontent.com/11181096/110843425-20df3300-825d-11eb-8598-679523ceb531.jpg)

**Comment by jahook** [comment]
![Milestones_add Sampling Protocol field to Sites module #45](https://user-images.githubusercontent.com/97756298/223285472-93ff0ca2-b7be-4832-87ec-c8518ea102a2.png)
All changes were made during the EMu upgrade.
