### ISSUE TITLE
Ecology Comments won't stretch

### ISSUE THREAD

**Issue by ljwalker** [LACMIP/emu#62]
**What module(s) and tab(s) does this bug affect?**
Taxonomy module: Ecology tab

**Describe the problem**
The _Comments_ field does not vertically stretch/enlarge when expanding the tab.

**Describe the solution you'd like**
Allow vertical stretching.

**Comment by jahook** [comment]
![Milestones_Ecology Comments won't stretch #62](https://user-images.githubusercontent.com/97756298/227665662-75e0d06a-ca4f-4699-a536-fa33178bc992.png)
All changes were made during the EMu upgrade.
